package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.UserLevel;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserLevel<M extends BaseUserLevel<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setDiscount(Integer discount) {
		set("discount", discount);
		return (M)this;
	}

	public Integer getDiscount() {
		return getInt("discount");
	}

	public M setCondition(Integer condition) {
		set("condition", condition);
		return (M)this;
	}

	public Integer getCondition() {
		return getInt("condition");
	}

	public M setSort(Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public Integer getSort() {
		return getInt("sort");
	}

	public M setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}

	public java.util.Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			UserLevel userLevel = UserLevel.getRecordById(getId());
			if(userLevel!=null){
				userLevel.setAddTime(new Date(0));
				userLevel.update();
			}
		}
		return get("addTime");
	}
}
