package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.Shop;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShop<M extends BaseShop<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setSummary(String summary) {
		set("summary", summary);
		return (M)this;
	}

	public String getSummary() {
		return getStr("summary");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}

	public String getAddress() {
		return getStr("address");
	}

	public M setPicture(String picture) {
		set("picture", picture);
		return (M)this;
	}

	public String getPicture() {
		return getStr("picture");
	}

	public M setNotice(String notice) {
		set("notice", notice);
		return (M)this;
	}

	public String getNotice() {
		return getStr("notice");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}

	public java.util.Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			Shop shop = Shop.getShopById(getId());
			if(shop!=null){
				shop.setAddTime(new Date(0));
				shop.update();
			}
		}
		return get("addTime");
	}

	public M setConfig(String config) {
		set("config", config);
		return (M)this;
	}

	public String getConfig() {
		return getStr("config");
	}

	public M setIsActive(Boolean isActive) {
		set("isActive", isActive);
		return (M)this;
	}

	public Boolean getIsActive() {
		return get("isActive");
	}

}
