package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.AdminLoginLog;
import com.pl23k.restaurant.model.Promotion;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePromotion<M extends BasePromotion<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setSummary(String summary) {
		set("summary", summary);
		return (M)this;
	}

	public String getSummary() {
		return getStr("summary");
	}

	public M setRule(String rule) {
		set("rule", rule);
		return (M)this;
	}

	public String getRule() {
		return getStr("rule");
	}

	public M setSort(Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public Integer getSort() {
		return getInt("sort");
	}

	public M setIsActive(Boolean isActive) {
		set("isActive", isActive);
		return (M)this;
	}

	public Boolean getIsActive() {
		return get("isActive");
	}

	public M setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}
	
	public java.util.Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			Promotion promotion = Promotion.getPromotionById(getId());
			if(promotion!=null){
				promotion.setAddTime(new Date(0));
				promotion.update();
			}
		}
		return get("addTime");
	}

}
