package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.Worker;
import com.sun.corba.se.spi.orbutil.threadpool.Work;
import com.sun.org.apache.xpath.internal.operations.Bool;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWorker<M extends BaseWorker<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setUsername(String username) {
		set("username", username);
		return (M)this;
	}

	public String getUsername() {
		return getStr("username");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}

	public String getPassword() {
		return getStr("password");
	}

	public M setRealName(String realName) {
		set("realName", realName);
		return (M)this;
	}

	public String getRealName() {
		return getStr("realName");
	}

	public M setSex(Boolean sex) {
		set("sex", sex);
		return (M)this;
	}

	public Boolean getSex() {
		return getBoolean("sex");
	}

	public M setBirthday(Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}

	public Date getBirthday() {
		return getDate("birthday");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}

	public String getAddress() {
		return getStr("address");
	}

	public M setAvatar(String avatar) {
		set("avatar", avatar);
		return (M)this;
	}

	public String getAvatar() {
		return getStr("avatar");
	}

	public M setWorkAddTime(Date workAddTime) {
		set("workAddTime", workAddTime);
		return (M)this;
	}

	public Date getWorkAddTime() {
		return getDate("workAddTime");
	}

	public M setAddTime(Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}

	public Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			Worker worker = Worker.getRecordById(getId());
			if(worker!=null){
				worker.setAddTime(new Date(0));
				worker.update();
			}
		}
		return getDate("addTime");
	}

	public M setIsActive(Boolean isActive){
		set("isActive",isActive);
		return (M)this;
	}

	public Boolean getIsActive(){
		return getBoolean("isActive");
	}

	public M setShopId(Integer shopId) {
		set("shopId", shopId);
		return (M)this;
	}

	public Integer getShopId() {
		return getInt("shopId");
	}

	public M setRoyaltyRate(Integer royaltyRate){
		set("royaltyRate",royaltyRate);
		return (M)this;
	}

	public Integer getRoyaltyRate(){
		return getInt("royaltyRate");
	}
}
