package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.AdminLoginLog;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConsume<M extends BaseConsume<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setMemberId(String memberId) {
		set("memberId", memberId);
		return (M)this;
	}

	public String getMemberId() {
		return getStr("memberId");
	}

	public M setWorkerId(Integer workerId) {
		set("workerId", workerId);
		return (M)this;
	}

	public Integer getWorkerId() {
		return getInt("workerId");
	}

	public M setPayTotalMoney(java.math.BigDecimal payTotalMoney) {
		set("payTotalMoney", payTotalMoney);
		return (M)this;
	}

	public java.math.BigDecimal getPayTotalMoney() {
		return get("payTotalMoney");
	}

	public M setTotalMoney(java.math.BigDecimal totalMoney) {
		set("totalMoney", totalMoney);
		return (M)this;
	}

	public java.math.BigDecimal getTotalMoney() {
		return get("totalMoney");
	}

	public M setMoney(java.math.BigDecimal money) {
		set("money", money);
		return (M)this;
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public M setCoin(java.math.BigDecimal coin) {
		set("coin", coin);
		return (M)this;
	}

	public java.math.BigDecimal getCoin() {
		return get("coin");
	}

	public M setEvidence(String evidence) {
		set("evidence", evidence);
		return (M)this;
	}

	public String getEvidence() {
		return getStr("evidence");
	}

	public M setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}

	public java.util.Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			AdminLoginLog admin = AdminLoginLog.getRecordById(getId());
			if(admin!=null){
				admin.setLoginTime(new Date(0));
				admin.update();
			}
		}
		return get("addTime");
	}

	public M setBeforeMoney(java.math.BigDecimal beforeMoney) {
		set("beforeMoney", beforeMoney);
		return (M)this;
	}

	public java.math.BigDecimal getBeforeMoney() {
		return get("beforeMoney");
	}

	public M setBeforeCoin(java.math.BigDecimal beforeCoin) {
		set("beforeCoin", beforeCoin);
		return (M)this;
	}

	public java.math.BigDecimal getBeforeCoin() {
		return get("beforeCoin");
	}

	public M setAfterMoney(java.math.BigDecimal afterMoney) {
		set("afterMoney", afterMoney);
		return (M)this;
	}

	public java.math.BigDecimal getAfterMoney() {
		return get("afterMoney");
	}

	public M setAfterCoin(java.math.BigDecimal afterCoin) {
		set("afterCoin", afterCoin);
		return (M)this;
	}

	public java.math.BigDecimal getAfterCoin() {
		return get("afterCoin");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setRejectAdmin(Integer rejectAdmin) {
		set("rejectAdmin", rejectAdmin);
		return (M)this;
	}

	public Integer getRejectAdmin() {
		return getInt("rejectAdmin");
	}

	public M setDiscount(Integer discount) {
		set("discount", discount);
		return (M)this;
	}

	public Integer getDiscount() {
		return getInt("discount");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
