package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setSiteName(String siteName) {
		set("siteName", siteName);
		return (M)this;
	}

	public String getSiteName() {
		return getStr("siteName");
	}

	public M setSiteUrl(String siteUrl) {
		set("siteUrl", siteUrl);
		return (M)this;
	}

	public String getSiteUrl() {
		return getStr("siteUrl");
	}

	public M setRecord(String record) {
		set("record", record);
		return (M)this;
	}

	public String getRecord() {
		return getStr("record");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}

	public String getEmail() {
		return getStr("email");
	}

	public M setCompany(String company) {
		set("company", company);
		return (M)this;
	}

	public String getCompany() {
		return getStr("company");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}

	public String getAddress() {
		return getStr("address");
	}

	public M setIsActive(Boolean isActive) {
		set("isActive", isActive);
		return (M)this;
	}

	public Boolean getIsActive() {
		return get("isActive");
	}

	public M setWxAppId(String wxAppId){
		set("wxAppId",wxAppId);
		return (M)this;
	}
	public String getWxAppId(){
		return get("wxAppId");
	}

	public M setWxAppSecret(String wxAppSecret){
		set("wxAppSecret",wxAppSecret);
		return (M)this;
	}
	public String getWxAppSecret(){
		return get("wxAppSecret");
	}

	public M setWxUserInfoCall(String wxUserInfoCall){
		set("wxUserInfoCall",wxUserInfoCall);
		return (M)this;
	}
	public String getWxUserInfoCall(){
		return get("wxUserInfoCall");
	}

	public M setWxLoginUrl(String wxLoginUrl){
		set("wxLoginUrl",wxLoginUrl);
		return (M)this;
	}
	public String getWxLoginUrl(){
		return get("wxLoginUrl");
	}

	public M setWxMchId(String wxMchId){
		set("wxMchId",wxMchId);
		return (M)this;
	}
	public String getWxMchId(){
		return get("wxMchId");
	}

	public M setWxPayApi(String wxPayApi){
		set("wxPayApi",wxPayApi);
		return (M)this;
	}
	public String getWxPayApi(){
		return get("wxPayApi");
	}

	public M setWxTemplateId(String wxTemplateId){
		set("wxTemplateId",wxTemplateId);
		return (M)this;
	}
	public String getWxTemplateId(){
		return get("wxTemplateId");
	}

	public M setWxRechargeMessageId(String wxRechargeMessageId){
		set("wxRechargeMessageId",wxRechargeMessageId);
		return (M)this;
	}
	public String getWxRechargeMessageId(){
		return get("wxRechargeMessageId");
	}
}
