package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.WechatUser;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatUser<M extends BaseWechatUser<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setMemberId(String memberId) {
		set("memberId", memberId);
		return (M)this;
	}

	public String getMemberId() {
		return getStr("memberId");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}

	public String getOpenId() {
		return getStr("openId");
	}

	public M setWechatId(String wechatId) {
		set("wechatId", wechatId);
		return (M)this;
	}

	public String getWechatId() {
		return getStr("wechatId");
	}

	public M setNickName(String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public String getNickName() {
		return getStr("nickName");
	}

	public M setSex(Boolean sex) {
		set("sex", sex);
		return (M)this;
	}

	public Boolean getSex() {
		return get("sex");
	}

	public M setAvatarUrl(String avatarUrl) {
		set("avatarUrl", avatarUrl);
		return (M)this;
	}

	public String getAvatarUrl() {
		return getStr("avatarUrl");
	}

	public M setAccessToken(String accessToken) {
		set("accessToken", accessToken);
		return (M)this;
	}

	public String getAccessToken() {
		return getStr("accessToken");
	}

	public M setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}

	public java.util.Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			WechatUser user = WechatUser.getRecordById(getId());
			if(user!=null){
				user.setAddTime(new Date(0));
				user.update();
			}
		}
		return get("addTime");
	}

	public M setAccessTokenTime(java.util.Date accessTokenTime) {
		set("accessTokenTime", accessTokenTime);
		return (M)this;
	}

	public java.util.Date getAccessTokenTime() {
		return get("accessTokenTime");
	}

	public M setUnionId(String unionId) {
		set("unionId", unionId);
		return (M)this;
	}

	public String getUnionId() {
		return getStr("unionId");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}

	public String getAddress() {
		return getStr("address");
	}

	public M setPrivilege(String privilege) {
		set("privilege", privilege);
		return (M)this;
	}

	public String getPrivilege() {
		return getStr("privilege");
	}

}
