package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.pl23k.restaurant.model.AdminLoginLog;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminLoginLog<M extends BaseAdminLoginLog<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setUsername(String username) {
		set("username", username);
		return (M)this;
	}
	
	public String getUsername() {
		return getStr("username");
	}

	public M setLoginIp(Integer loginIp) {
		set("loginIp", loginIp);
		return (M)this;
	}
	
	public Integer getLoginIp() {
		return getInt("loginIp");
	}

	public M setLoginArea(String loginArea) {
		set("loginArea", loginArea);
		return (M)this;
	}
	
	public String getLoginArea() {
		return getStr("loginArea");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("loginTime", loginTime);
		return (M)this;
	}
	
	public java.util.Date getLoginTime() {
		if(get("loginTime")==null){
			set("loginTime",new Date(0));
			AdminLoginLog admin = AdminLoginLog.getRecordById(getId());
			if(admin!=null){
				admin.setLoginTime(new Date(0));
				admin.update();
			}
		}
		return get("loginTime");
	}

}
