package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.Admin;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setUsername(String username) {
		set("username", username);
		return (M)this;
	}

	public String getUsername() {
		return getStr("username");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}

	public String getPassword() {
		return getStr("password");
	}

	public M setRealName(String realName) {
		set("realName", realName);
		return (M)this;
	}

	public String getRealName() {
		return getStr("realName");
	}

	public M setRole(Integer role) {
		set("role", role);
		return (M)this;
	}

	public Integer getRole() {
		return getInt("role");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}

	public String getEmail() {
		return getStr("email");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("lastLoginTime", lastLoginTime);
		return (M)this;
	}

	public java.util.Date getLastLoginTime() {
		return get("lastLoginTime");
	}

	public M setLastLoginIp(Integer lastLoginIp) {
		set("lastLoginIp", lastLoginIp);
		return (M)this;
	}

	public Integer getLastLoginIp() {
		return getInt("lastLoginIp");
	}

	public M setLastLoginArea(String lastLoginArea) {
		set("lastLoginArea", lastLoginArea);
		return (M)this;
	}

	public String getLastLoginArea() {
		return getStr("lastLoginArea");
	}

	public M setCurLoginTime(java.util.Date curLoginTime) {
		set("curLoginTime", curLoginTime);
		return (M)this;
	}

	public java.util.Date getCurLoginTime() {
		return get("curLoginTime");
	}

	public M setCurLoginIp(Integer curLoginIp) {
		set("curLoginIp", curLoginIp);
		return (M)this;
	}

	public Integer getCurLoginIp() {
		return getInt("curLoginIp");
	}

	public M setCurLoginArea(String curLoginArea) {
		set("curLoginArea", curLoginArea);
		return (M)this;
	}

	public String getCurLoginArea() {
		return getStr("curLoginArea");
	}

	public M setAddTime(java.util.Date addTime) {
				set("addTime", addTime);
				return (M)this;
			}

	public java.util.Date getAddTime() {
		if(get("addTime")==null){
			set("addTime",new Date(0));
			Admin admin = Admin.getAdminById(getId());
			if(admin!=null){
				admin.setAddTime(new Date(0));
				admin.update();
			}
		}
		return get("addTime");
	}

	public M setShopId(Integer shopId) {
		set("shopId", shopId);
		return (M)this;
	}

	public Integer getShopId() {
		return getInt("shopId");
	}

	public M setRoyalty(Integer royalty) {
		set("royalty", royalty);
		return (M)this;
	}

	public Integer getRoyalty() {
		return getInt("royalty");
	}

}
