package com.pl23k.restaurant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pl23k.restaurant.model.RechargePayOrderWechat;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechargePayOrderWechat<M extends BaseRechargePayOrderWechat<M>> extends Model<M> implements IBean {

	public M setPayId(String payId) {
		set("payId", payId);
		return (M)this;
	}

	public String getPayId() {
		return getStr("payId");
	}

	public M setAppId(String appId) {
		set("appId", appId);
		return (M)this;
	}

	public String getAppId() {
		return getStr("appId");
	}

	public M setMchId(String mchId) {
		set("mchId", mchId);
		return (M)this;
	}

	public String getMchId() {
		return getStr("mchId");
	}

	public M setSeqNo(String seqNo) {
		set("seqNo", seqNo);
		return (M)this;
	}

	public String getSeqNo() {
		return getStr("seqNo");
	}

	public M setNonceStr(String nonceStr) {
		set("nonceStr", nonceStr);
		return (M)this;
	}

	public String getNonceStr() {
		return getStr("nonceStr");
	}

	public M setSign(String sign) {
		set("sign", sign);
		return (M)this;
	}

	public String getSign() {
		return getStr("sign");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}

	public String getOpenId() {
		return getStr("openId");
	}

	public M setIsSubscribe(Boolean isSubscribe) {
		set("isSubscribe", isSubscribe);
		return (M)this;
	}

	public Boolean getIsSubscribe() {
		return get("isSubscribe");
	}

	public M setTradeType(String tradeType) {
		set("tradeType", tradeType);
		return (M)this;
	}

	public String getTradeType() {
		return getStr("tradeType");
	}

	public M setBankType(String bankType) {
		set("bankType", bankType);
		return (M)this;
	}

	public String getBankType() {
		return getStr("bankType");
	}

	public M setTotalFee(Integer totalFee) {
		set("totalFee", totalFee);
		return (M)this;
	}

	public Integer getTotalFee() {
		return getInt("totalFee");
	}

	public M setFeeType(String feeType) {
		set("feeType", feeType);
		return (M)this;
	}

	public String getFeeType() {
		return getStr("feeType");
	}

	public M setCashFee(Integer cashFee) {
		set("cashFee", cashFee);
		return (M)this;
	}

	public Integer getCashFee() {
		return getInt("cashFee");
	}

	public M setCashFeeType(String cashFeeType) {
		set("cashFeeType", cashFeeType);
		return (M)this;
	}

	public String getCashFeeType() {
		return getStr("cashFeeType");
	}

	public M setCouponFee(Integer couponFee) {
		set("couponFee", couponFee);
		return (M)this;
	}

	public Integer getCouponFee() {
		return getInt("couponFee");
	}

	public M setCouponCount(Integer couponCount) {
		set("couponCount", couponCount);
		return (M)this;
	}

	public Integer getCouponCount() {
		return getInt("couponCount");
	}

	public M setCouponIds(String couponIds) {
		set("couponIds", couponIds);
		return (M)this;
	}

	public String getCouponIds() {
		return getStr("couponIds");
	}

	public M setCouponFees(String couponFees) {
		set("couponFees", couponFees);
		return (M)this;
	}

	public String getCouponFees() {
		return getStr("couponFees");
	}

	public M setOutTradeNo(String outTradeNo) {
		set("outTradeNo", outTradeNo);
		return (M)this;
	}

	public String getOutTradeNo() {
		return getStr("outTradeNo");
	}

	public M setAttach(String attach) {
		set("attach", attach);
		return (M)this;
	}

	public String getAttach() {
		return getStr("attach");
	}

	public M setTimeEnd(java.util.Date timeEnd) {
		set("timeEnd", timeEnd);
		return (M)this;
	}
	
	public java.util.Date getTimeEnd() {
		if(get("timeEnd")==null){
			set("timeEnd",new Date(0));
			RechargePayOrderWechat recharge = RechargePayOrderWechat.getRecordById(getPayId());
			if(recharge!=null){
				recharge.setTimeEnd(new Date(0));
				recharge.update();
			}
		}
		return get("timeEnd");
	}

}
