package com.pl23k.restaurant.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_admin", "id", Admin.class);
		arp.addMapping("tb_admin_login_log", "id", AdminLoginLog.class);
		arp.addMapping("tb_config", "id", Config.class);
		arp.addMapping("tb_consume", "id", Consume.class);
		arp.addMapping("tb_promotion", "id", Promotion.class);
		arp.addMapping("tb_recharge_order", "id", RechargeOrder.class);
		arp.addMapping("tb_recharge_pay_order_wechat", "payId", RechargePayOrderWechat.class);
		arp.addMapping("tb_shop", "id", Shop.class);
		arp.addMapping("tb_user", "id", User.class);
		arp.addMapping("tb_user_level", "id", UserLevel.class);
		arp.addMapping("tb_wechat_user", "id", WechatUser.class);
		arp.addMapping("tb_worker", "id", Worker.class);
	}
}

