package com.pl23k.restaurant.model;

import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.TableMapping;
import com.pl23k.restaurant.model.base.BaseAdmin;
import com.pl23k.restaurant.utils.DESUtil;
import com.pl23k.restaurant.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
	public static final String tableName = TableMapping.me().getTable(Admin.class).getName();
	public static int mPageSize = 10;

	/**
	 * 通过ID获取管理员
	 * @param id
	 * @return
	 */
	public static Admin getAdminById(Integer id){
		Admin admin = null;
		try{
			admin = dao.findById(id);
		}catch (Exception e){
			e.printStackTrace();
		}
		return admin;
	}

	/**
	 * 通过用户名获取管理员
	 * @param username
	 * @return
	 */
	public static Admin getAdminByUsername(String username){
		Admin admin = null;
		try{
			admin = dao.findFirst(String.format("select * from %s where username=?",tableName),username);
		}catch (Exception e){
			e.printStackTrace();
		}
		return admin;
	}

	/**
	 * 通过ID获取管理员姓名
	 * @param id
	 * @return
	 */
	public static String getRealNameById(Integer id){
		String name = null;
		try{
			Admin admin = dao.findById(id);
			if(admin !=null){
				name = admin.getRealName();
			}
		}catch (Exception e ){
			e.printStackTrace();
		}
		return name;
	}

	/**
	 * 通过ID获取管理员用户名
	 * @param id
	 * @return
	 */
	public static String getUsernameById(Integer id){
		String name = null;
		try{
			Admin admin = dao.findById(id);
			if(admin !=null){
				name = admin.getUsername();
			}
		}catch (Exception e ){
			e.printStackTrace();
		}
		return name;
	}

	/**
	 * 获取名称第一个字
	 * @return
	 */
	public String getFirstName(){
		String name = null;
		try{
			name = getRealName().substring(0,1);
		}catch (Exception e){
			e.printStackTrace();
		}
		return name;
	}

	/**
	 * 获得上次登录ip，将int型转为字符串型
	 * @return
	 */
	public String getLastLoginIpString(){
		String ipStr = "";
		try {
			int ipInt = getLastLoginIp();
			ipStr = Utils.intToStringByByte(ipInt,".");
		}catch (Exception e){
			e.printStackTrace();
			ipStr = "0.0.0.0";
		}
		return ipStr;
	}

	/**
	 * 分页取出管理员信息
	 * @param pageNumber
	 * @return
	 */
	public static Page<Admin> getAdminByPage(int pageNumber){
		Page<Admin> page = null;
		try {
			page = dao.paginate(pageNumber, mPageSize, "select * ", String.format("from %s order by id desc", tableName));
		}catch (Exception e){
			e.printStackTrace();
		}
		return page;
	}

	/**
	 *  获取明文密码
	 */
	public String getTruePassword(){
		String pass = null;
		try{
			pass = DESUtil.decryStr(getPassword());
		}catch (Exception e){
			e.printStackTrace();
		}
		return pass;
	}

	public String getShopName(){
		String name = "无";
		try{
			if(getShopId()!=null && getShopId()>0){
				Shop shop = Shop.getShopById(getShopId());
				if(shop!=null){
					name = shop.getName();
				}
			}
		}catch (Exception e){
			e.printStackTrace();
		}
		return name;
	}

}
