package com.pl23k.restaurant.model;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.TableMapping;
import com.pl23k.restaurant.model.base.BaseAdminLoginLog;
import com.pl23k.restaurant.utils.IPLocation.IPUtils;
import com.pl23k.restaurant.utils.IPLocation.Locator;
import com.pl23k.restaurant.utils.Utils;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminLoginLog extends BaseAdminLoginLog<AdminLoginLog> {
	public static final AdminLoginLog dao = new AdminLoginLog().dao();
	public static final String tableName = TableMapping.me().getTable(AdminLoginLog.class).getName();
	public static int mPageSize = 10;


	public static AdminLoginLog getRecordById(Integer id){
	    AdminLoginLog adminLoginLog = null;
	    try{
	        adminLoginLog = dao.findById(id);
        }catch (Exception e){
	        e.printStackTrace();
        }
	    return adminLoginLog;
    }

	public static void addLoginLog(Admin admin,String ip){
        try {
            if (admin!=null && admin.getId() > 0 && StrKit.notBlank(ip)) {
                int iip = IPUtils.ipToInt(ip);
                AdminLoginLog loginLog = new AdminLoginLog();
                String region = Locator.getFullAddr(ip);
                if (region == null || region.length() < 1) {
                    region = "未知";
                }
                loginLog.setUsername(admin.getUsername())
                        .setLoginIp(iip)
                        .setLoginArea(region)
                        .setLoginTime(new Date())
                        .save();
                admin.setLastLoginIp(admin.getCurLoginIp())
                        .setLastLoginArea(admin.getCurLoginArea())
                        .setLastLoginTime(admin.getCurLoginTime()==null? new Date():admin.getCurLoginTime())
                        .setCurLoginIp(iip)
                        .setCurLoginArea(region)
                        .setCurLoginTime(loginLog.getLoginTime())
                        .update();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * 获得登录ip，将int型转为字符串型
     * @return
     */
    public String getLoginIpString(){
        String ipStr = "";
        try {
            int ipInt = getLoginIp();
            ipStr = Utils.intToStringByByte(ipInt,".");
        }catch (Exception e){
            e.printStackTrace();
            ipStr = "0.0.0.0";
        }
        return ipStr;
    }
}
