package com.pl23k.restaurant.model;

import com.jfinal.plugin.activerecord.TableMapping;
import com.pl23k.restaurant.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config().dao();
	public static final String tableName = TableMapping.me().getTable(Config.class).getName();
	public static int mPageSize = 10;

	/**
	 * 获取配置
	 * @return
	 */
	public static Config getConfig(){
		return getConfigById(1);
	}

	/**
	 * 通过ID获取配置
	 * @param id
	 * @return
	 */
	public static Config getConfigById(Integer id){
		Config config = null;
		try{
			config = dao.findById(id);
		}catch (Exception e){
			e.printStackTrace();
		}
		return config;
	}
}
