package com.pl23k.restaurant.model;

import com.jfinal.plugin.activerecord.TableMapping;
import com.pl23k.restaurant.model.base.BaseRechargePayOrderWechat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechargePayOrderWechat extends BaseRechargePayOrderWechat<RechargePayOrderWechat> {
	public static final RechargePayOrderWechat dao = new RechargePayOrderWechat().dao();
	public static final String tableName = TableMapping.me().getTable(RechargePayOrderWechat.class).getName();
	public static int mPageSize = 10;

	/**
	 * 通过ID获取记录
	 * @param payId
	 * @return
	 */
	public static RechargePayOrderWechat getRecordById(String payId){
		RechargePayOrderWechat record = null;
		try{
			record = dao.findById(payId);
		}catch (Exception e){
			e.printStackTrace();
		}
		return record;
	}

	/**
	 * 通过ID获取微信支付订单
	 * @param payId
	 * @return
	 */
	public static RechargePayOrderWechat getPayOrderByPayId(String payId){
		RechargePayOrderWechat payOrderWechat = null;
		try{
			payOrderWechat = dao.findFirst(String.format("select * from %s where payId=?",tableName),payId);
		}catch (Exception e){
			e.printStackTrace();
		}
		return payOrderWechat;
	}
}
