package com.pl23k.restaurant.model;

import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.TableMapping;
import com.pl23k.restaurant.model.base.BaseUserLevel;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLevel extends BaseUserLevel<UserLevel> {
	public static final UserLevel dao = new UserLevel().dao();
	public static final String tableName = TableMapping.me().getTable(UserLevel.class).getName();
	public static int mPageSize = 10;

	 /**
	 * 通过ID获取记录
	 * @param id
	 * @return
	 */
	public static UserLevel getRecordById(Integer id){
		UserLevel userLevel = null;
		try{
			userLevel = dao.findById(id);
		}catch (Exception e){
			e.printStackTrace();
		}
		return userLevel;
	}

	/**
	 * 分页取出记录
	 * @param pageNumber
	 * @return
	 */
	public static Page<UserLevel> getRecordByPage(int pageNumber){
		Page<UserLevel> page = null;
		try {
			page = dao.paginate(pageNumber, mPageSize, "select * ", String.format("from %s order by id desc", tableName));
		}catch (Exception e){
			e.printStackTrace();
		}
		return page;
	}

	/**
	 * 通过ID获取等级名称
	 * @param id
	 * @return
	 */
	public static String getLevelNameById(Integer id){
		String name = null;
		try{
			UserLevel userLevel = dao.findById(id);
			if(userLevel!=null){
				name = userLevel.getName();
			}
		}catch (Exception e){
			e.printStackTrace();
		}
		return name;
	}

	/**
	 * 根据排序获取等级列表
	 * @return
	 */
	public static List<UserLevel> getUserLevelListBySort(){
		List<UserLevel> userLevels = null;
		try{
			userLevels = dao.find(String.format("select * from %s order by sort",tableName));
		}catch (Exception e){
			e.printStackTrace();
		}
		return userLevels;
	}
}
