package com.pl23k.restaurant.model;

import com.jfinal.plugin.activerecord.TableMapping;
import com.pl23k.restaurant.model.base.BaseWechatUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatUser extends BaseWechatUser<WechatUser> {
	public static final WechatUser dao = new WechatUser().dao();
	public static final String tableName = TableMapping.me().getTable(WechatUser.class).getName();
	public static int mPageSize = 10;

	/**
	 * 通过ID获取记录
	 * @param id
	 * @return
	 */
	public static WechatUser getRecordById(Integer id){
		WechatUser record = null;
		try{
			record = dao.findById(id);
		}catch (Exception e){
			e.printStackTrace();
		}
		return record;
	}

	public static WechatUser getWechatUserByOpenId(String openId){
		WechatUser wechatUser = null;
		try{
			wechatUser = dao.findFirst(String.format("select * from %s where openid=?",tableName),openId);
		}catch (Exception e){
			e.printStackTrace();
		}
		return wechatUser;
	}

	public static WechatUser getWechatUserByMemberId(String memberId){
		WechatUser wechatUser = null;
		try{
			wechatUser = dao.findFirst(String.format("select * from %s where memberId=?",tableName),memberId);
		}catch (Exception e){
			e.printStackTrace();
		}
		return wechatUser;
	}
}
